export const products = [
  {
    id: 1,
    name: "Alloy Wheels",
    price: 12000,
    image: "images/products/alloy_wheels.jpg",
    description: "Premium alloy wheels with matte finish. Set of 4, 15-inch size.",
    category: "Performance Upgrades",
    brand: "NeoWheels",
    model: "Maruti Baleno",
    compatibleYears: "2017–2022",
    condition: "New",
    stock: 8,
    sellerName: "SpeedParts Hub",
    sellerContact: "+91-9876543210",
    location: "Delhi",
    rating: 4.7,
    isFeatured: true
  },
  {
    id: 2,
    name: "Fog Lights",
    price: 2500,
    image: "images/products/fog_lights.jpg",
    description: "Bright white LED fog lights with waterproof housing.",
    category: "Lighting Mods",
    brand: "Hella",
    model: "Hyundai i20",
    compatibleYears: "2015–2019",
    condition: "New",
    stock: 12,
    sellerName: "BrightMods",
    sellerContact: "+91-9911223344",
    location: "Kolkata",
    rating: 4.5,
    isFeatured: false
  },
  {
    id: 3,
    name: "Steering Cover",
    price: 750,
    image: "images/products/steering_cover.jpg",
    description: "Black and red stitched leather steering cover for premium feel.",
    category: "Interior Mods & Comfort",
    brand: "AutoStyle",
    model: "Universal Fit",
    compatibleYears: "All",
    condition: "New",
    stock: 30,
    sellerName: "DrivePro",
    sellerContact: "+91-9988776655",
    location: "Mumbai",
    rating: 4.2,
    isFeatured: false
  },
  {
    id: 4,
    name: "Rear Spoiler",
    price: 5000,
    image: "images/products/rear_spoiler.jpg",
    description: "Gloss black rear spoiler for hatchbacks with aerodynamic design.",
    category: "Body Kits & Custom Styling",
    brand: "Sparco",
    model: "Tata Altroz",
    compatibleYears: "2020–2024",
    condition: "New",
    stock: 5,
    sellerName: "AutoMods",
    sellerContact: "+91-9123456789",
    location: "Chennai",
    rating: 4.6,
    isFeatured: true
  },
  {
    id: 5,
    name: "Dash Cam",
    price: 4500,
    image: "images/products/dash_cam.jpg",
    description: "Full HD 1080p dash cam with night vision and loop recording.",
    category: "Smart Tech & Infotainment",
    brand: "Qubo",
    model: "Universal Fit",
    compatibleYears: "All",
    condition: "New",
    stock: 20,
    sellerName: "CamSecure",
    sellerContact: "+91-9090909090",
    location: "Delhi",
    rating: 4.8,
    isFeatured: true
  },
  {
    id: 6,
    name: "Air Freshener",
    price: 300,
    image: "images/products/air_freshener.jpg",
    description: "Long-lasting citrus fragrance gel-type freshener.",
    category: "Interior Mods & Comfort",
    brand: "Ambi Pur",
    model: "Universal Fit",
    compatibleYears: "All",
    condition: "New",
    stock: 50,
    sellerName: "FreshRiders",
    sellerContact: "+91-8888555577",
    location: "Kolkata",
    rating: 4.1,
    isFeatured: false
  },
  {
    id: 7,
    name: "Car Vacuum Cleaner",
    price: 1100,
    image: "images/products/vacuum_cleaner.jpg",
    description: "Portable vacuum cleaner with powerful suction and HEPA filter.",
    category: "Detailing & Shine Garage",
    brand: "Bergmann",
    model: "Universal Fit",
    compatibleYears: "All",
    condition: "New",
    stock: 15,
    sellerName: "CleanAuto India",
    sellerContact: "+91-7676767676",
    location: "Bangalore",
    rating: 4.4,
    isFeatured: false
  },
  {
    id: 8,
    name: "Tool Kit Set",
    price: 800,
    image: "images/products/tool_kit.jpg",
    description: "Essential 23-piece tool kit for all types of car repairs.",
    category: "Hidden Essentials",
    brand: "Taparia",
    model: "Universal Fit",
    compatibleYears: "All",
    condition: "New",
    stock: 25,
    sellerName: "MechanicMart",
    sellerContact: "+91-7766554433",
    location: "Pune",
    rating: 4.3,
    isFeatured: false
  },
  {
    id: 9,
    name: "Car Wrap Vinyl",
    price: 1500,
    image: "images/products/wrap_vinyl.jpg",
    description: "Gloss black vinyl wrap roll, 5ft x 6ft, stretchable and waterproof.",
    category: "Body Kits & Custom Styling",
    brand: "3M",
    model: "Universal Fit",
    compatibleYears: "All",
    condition: "New",
    stock: 18,
    sellerName: "WrapZone",
    sellerContact: "+91-8888123123",
    location: "Delhi",
    rating: 4.5,
    isFeatured: true
  },
  {
    id: 10,
    name: "Car Alarm System",
    price: 3000,
    image: "images/products/alarm_system.jpg",
    description: "Smart remote car alarm system with anti-theft and mobile alert.",
    category: "Smart Tech & Infotainment",
    brand: "Autocop",
    model: "Universal Fit",
    compatibleYears: "All",
    condition: "New",
    stock: 10,
    sellerName: "SecureDrive",
    sellerContact: "+91-7000123456",
    location: "Hyderabad",
    rating: 4.6,
    isFeatured: true
  }
];
